/**
 * Hook Service
 *
 * Manages Claude Code hooks for workflow enforcement.
 * Handles .claude/settings.json and hook scripts.
 */

import { readTextFile, writeTextFile, exists, mkdir, remove } from '@tauri-apps/plugin-fs';
import type { WorkflowStep } from '../types';
import { resetWorkflow } from './workflowService';

// Claude settings.json structure
export interface ClaudeHookConfig {
  type: 'command';
  command: string;
  timeout?: number;
}

export interface ClaudeHookMatcher {
  matcher: string;
  hooks: ClaudeHookConfig[];
}

export interface ClaudeSettings {
  hooks?: {
    PreToolUse?: ClaudeHookMatcher[];
    PostToolUse?: ClaudeHookMatcher[];
    [key: string]: ClaudeHookMatcher[] | undefined;
  };
  _workflow_managed?: boolean;
  [key: string]: unknown;
}

export interface HookResult {
  success: boolean;
  error?: string;
}

// ============================================
// Read/Write Claude Settings
// ============================================

/**
 * Read Claude settings.json from project
 */
export async function readClaudeSettings(projectPath: string): Promise<ClaudeSettings | null> {
  try {
    const settingsPath = `${projectPath}/.claude/settings.json`;
    const fileExists = await exists(settingsPath);

    if (!fileExists) {
      return null;
    }

    const content = await readTextFile(settingsPath);
    return JSON.parse(content);
  } catch (e) {
    console.error('[HookService] Error reading settings:', e);
    return null;
  }
}

/**
 * Write Claude settings.json to project
 */
export async function writeClaudeSettings(
  projectPath: string,
  settings: ClaudeSettings
): Promise<boolean> {
  try {
    const claudeDir = `${projectPath}/.claude`;
    const settingsPath = `${claudeDir}/settings.json`;

    // Ensure .claude directory exists
    const dirExists = await exists(claudeDir);
    if (!dirExists) {
      await mkdir(claudeDir, { recursive: true });
    }

    const content = JSON.stringify(settings, null, 2);
    await writeTextFile(settingsPath, content);
    return true;
  } catch (e) {
    console.error('[HookService] Error writing settings:', e);
    return false;
  }
}

// ============================================
// Workflow Skill Generation
// ============================================

/**
 * Generate the /workflow skill for Claude Code
 */
export function generateWorkflowSkill(projectPath: string): string {
  return `---
name: workflow
description: Gestiona el workflow de flujo controlado. Usa para ver estado, avanzar, resetear o ir a un step específico del workflow.
user-invocable: true
---

# Workflow Management

Gestiona el workflow de flujo controlado para este proyecto.

## Subcomandos

Parsea \`$ARGUMENTS\` para determinar la acción:

- **vacío o "status"** → Mostrar estado actual
- **"advance"** → Avanzar al siguiente step
- **"reset"** → Resetear a step 0
- **"set N"** → Ir directamente al step N

## Ejecución

El \`project_dir\` para este proyecto es: \`${projectPath}\`

### Para status (default):
Llama a \`mcp__workflow-manager__workflow_status\` con \`project_dir="${projectPath}"\`.

Muestra el resultado en formato tabla:
\`\`\`
Workflow: Step {current_step} - {step_name}

| # | Nombre | Estado | Bloqueados |
|---|--------|--------|------------|
\`\`\`

### Para advance:
Llama a \`mcp__workflow-manager__workflow_advance\` con \`project_dir="${projectPath}"\`.
Confirma: "Avanzado a Step N - {nombre}"

### Para reset:
Llama a \`mcp__workflow-manager__workflow_reset\` con \`project_dir="${projectPath}"\`.
Confirma: "Workflow reseteado a Step 0"

### Para set N:
Llama a \`mcp__workflow-manager__workflow_set_step\` con \`project_dir="${projectPath}"\` y \`step_index=N\`.
Confirma: "Workflow en Step N - {nombre}"

## Notas

- Write/Edit están bloqueados en steps 0 y 1
- Usa \`/workflow advance\` o \`/workflow set 2\` para desbloquear
`;
}

// Workflow Enforcer Script Generation
// ============================================

/**
 * Generate the Python workflow enforcer script
 */
export function generateWorkflowEnforcerScript(projectPath: string): string {
  return `#!/usr/bin/env python3
"""
Workflow Enforcer Hook for Claude Code
Generated by AgentCockpit
"""

import json
import sys
import os
from pathlib import Path

def main():
    # Read hook input from stdin
    try:
        hook_input = json.load(sys.stdin)
    except json.JSONDecodeError:
        # If no input or invalid JSON, approve by default
        print(json.dumps({"decision": "approve"}))
        return

    tool_name = hook_input.get("tool_name", "")

    # Get project directory from environment
    project_dir = os.environ.get("CLAUDE_PROJECT_DIR", "${projectPath}")
    workflow_dir = Path(project_dir) / ".claude" / "workflow"

    # Check if enforcer is enabled via config
    config_file = workflow_dir / "config.json"
    if config_file.exists():
        try:
            with open(config_file, 'r') as f:
                config = json.load(f)
            if not config.get("enforcer_enabled", True):
                # Enforcer is disabled, approve all
                print(json.dumps({"decision": "approve"}))
                return
        except Exception:
            pass  # If config read fails, continue with normal logic

    # Read current state
    state_file = workflow_dir / "state.json"
    steps_file = workflow_dir / "steps.yaml"

    if not state_file.exists() or not steps_file.exists():
        # No workflow configured, approve all
        print(json.dumps({"decision": "approve"}))
        return

    try:
        with open(state_file, 'r') as f:
            state = json.load(f)

        current_step = state.get("current_step", 0)

        # Parse steps.yaml to get current step config
        # Simple YAML parsing (basic implementation)
        with open(steps_file, 'r') as f:
            steps_content = f.read()

        # Extract tools_blocked for current step
        steps = parse_steps_yaml(steps_content)

        if current_step < len(steps):
            step = steps[current_step]
            tools_blocked = step.get("tools_blocked", [])

            # Check if tool is blocked
            if tool_name in tools_blocked:
                print(json.dumps({
                    "decision": "block",
                    "message": f"Tool '{tool_name}' is blocked at step {current_step} ({step.get('name', 'Unknown')}). Complete this step first."
                }))
                return
    except Exception as e:
        # On error, approve to avoid blocking legitimate work
        print(json.dumps({"decision": "approve"}))
        return

    print(json.dumps({"decision": "approve"}))

def parse_steps_yaml(content: str) -> list:
    """Simple YAML parser for steps configuration"""
    steps = []
    current_step = None
    current_list = None

    for line in content.split('\\n'):
        stripped = line.strip()

        if not stripped or stripped.startswith('#'):
            continue

        if stripped.startswith('- id:'):
            if current_step is not None:
                steps.append(current_step)
            # Extract id value
            id_val = stripped.split(':', 1)[1].strip().strip('"').strip("'")
            current_step = {"id": id_val, "tools_blocked": [], "mcps_enabled": []}
            current_list = None
            continue

        if current_step is not None:
            if stripped.startswith('- ') and current_list:
                value = stripped[2:].strip().strip('"').strip("'")
                current_step[current_list].append(value)
            elif ':' in stripped:
                key, val = stripped.split(':', 1)
                key = key.strip()
                val = val.strip().strip('"').strip("'")

                if not val:
                    current_list = key
                    if key not in current_step:
                        current_step[key] = []
                else:
                    current_step[key] = val
                    current_list = None

    if current_step is not None:
        steps.append(current_step)

    return steps

if __name__ == "__main__":
    main()
`;
}

// ============================================
// Hook Installation
// ============================================

/**
 * Install workflow hooks into a project
 */
export async function installWorkflowHooks(
  projectPath: string,
  _steps?: WorkflowStep[]  // Kept for future use (e.g., generating step-specific hooks)
): Promise<HookResult> {
  try {
    // 1. Ensure .claude/hooks directory exists
    const hooksDir = `${projectPath}/.claude/hooks`;
    const hooksDirExists = await exists(hooksDir);
    if (!hooksDirExists) {
      await mkdir(hooksDir, { recursive: true });
    }

    // 2. Generate and write enforcer script
    const enforcerPath = `${hooksDir}/workflow_enforcer.py`;
    const enforcerScript = generateWorkflowEnforcerScript(projectPath);
    await writeTextFile(enforcerPath, enforcerScript);

    // 2.5. Initialize workflow state (state.json at step 0)
    await resetWorkflow(projectPath);
    console.log('[HookService] Workflow state initialized at step 0');

    // 2.6. Create /workflow skill for Claude Code
    const skillsDir = `${projectPath}/.claude/skills/workflow`;
    const skillsDirExists = await exists(skillsDir);
    if (!skillsDirExists) {
      await mkdir(skillsDir, { recursive: true });
    }
    const skillPath = `${skillsDir}/SKILL.md`;
    const skillContent = generateWorkflowSkill(projectPath);
    await writeTextFile(skillPath, skillContent);
    console.log('[HookService] Workflow skill created at', skillPath);

    // 3. Read existing settings (preserve other hooks)
    let settings = await readClaudeSettings(projectPath) || {};

    // 4. Add workflow hook configuration
    const workflowHook: ClaudeHookConfig = {
      type: 'command',
      command: `python3 "$CLAUDE_PROJECT_DIR/.claude/hooks/workflow_enforcer.py"`,
      timeout: 5
    };

    const workflowMatcher: ClaudeHookMatcher = {
      matcher: '*',
      hooks: [workflowHook]
    };

    // Initialize hooks if not present
    if (!settings.hooks) {
      settings.hooks = {};
    }

    // Get existing PreToolUse hooks (filter out any previous workflow hooks)
    const existingPreToolUse = (settings.hooks.PreToolUse || []).filter(
      matcher => !matcher.hooks.some(h => h.command.includes('workflow_enforcer'))
    );

    // Add workflow matcher
    settings.hooks.PreToolUse = [...existingPreToolUse, workflowMatcher];
    settings._workflow_managed = true;

    // 5. Write settings
    const success = await writeClaudeSettings(projectPath, settings);

    if (!success) {
      return { success: false, error: 'Failed to write settings.json' };
    }

    // 6. Install AS.md and update CLAUDE.md
    await installAsMarkdown(projectPath);

    console.log('[HookService] Workflow hooks installed successfully');
    return { success: true };
  } catch (e) {
    const error = e instanceof Error ? e.message : String(e);
    console.error('[HookService] Install error:', error);
    return { success: false, error };
  }
}

/**
 * Uninstall workflow hooks from a project
 */
export async function uninstallWorkflowHooks(projectPath: string): Promise<HookResult> {
  try {
    // 1. Read existing settings
    const settings = await readClaudeSettings(projectPath);

    if (settings && settings.hooks) {
      // Remove workflow hooks from PreToolUse
      if (settings.hooks.PreToolUse) {
        settings.hooks.PreToolUse = settings.hooks.PreToolUse.filter(
          matcher => !matcher.hooks.some(h => h.command.includes('workflow_enforcer'))
        );

        // Clean up empty array
        if (settings.hooks.PreToolUse.length === 0) {
          delete settings.hooks.PreToolUse;
        }
      }

      // Clean up empty hooks object
      if (Object.keys(settings.hooks).length === 0) {
        delete settings.hooks;
      }

      delete settings._workflow_managed;

      // Write updated settings
      await writeClaudeSettings(projectPath, settings);
    }

    // 2. Remove enforcer script
    const enforcerPath = `${projectPath}/.claude/hooks/workflow_enforcer.py`;
    const enforcerExists = await exists(enforcerPath);
    if (enforcerExists) {
      await remove(enforcerPath);
    }

    console.log('[HookService] Workflow hooks uninstalled successfully');
    return { success: true };
  } catch (e) {
    const error = e instanceof Error ? e.message : String(e);
    console.error('[HookService] Uninstall error:', error);
    return { success: false, error };
  }
}

// ============================================
// Hook Status
// ============================================

/**
 * Check if workflow hooks are installed in a project
 */
export async function isWorkflowHooksInstalled(projectPath: string): Promise<boolean> {
  try {
    const settings = await readClaudeSettings(projectPath);

    if (!settings || !settings.hooks || !settings.hooks.PreToolUse) {
      return false;
    }

    // Check if workflow hook is present
    return settings.hooks.PreToolUse.some(
      matcher => matcher.hooks.some(h => h.command.includes('workflow_enforcer'))
    );
  } catch (e) {
    console.error('[HookService] Error checking installation:', e);
    return false;
  }
}

/**
 * Sync workflow hooks based on enabled state
 * Instead of installing/uninstalling, we now write a config file
 * that the hook reads to determine if it should enforce or not.
 */
// ============================================
// Reindex Hooks (DeltaCodeCube)
// ============================================

/**
 * Generate a Python script for PostToolUse reindex trigger.
 * Fire-and-forget: uses subprocess.Popen so it doesn't block the agent.
 */
export function generateReindexHookScript(agentcockpitPath: string): string {
  return `#!/usr/bin/env python3
"""
DeltaCodeCube Reindex Hook for Claude Code
Generated by AgentCockpit

Triggers a non-blocking reindex after file modifications.
"""

import json
import sys
import subprocess
import os

def main():
    # Read hook input from stdin
    try:
        hook_input = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        return

    tool_name = hook_input.get("tool_name", "")

    # Only trigger on file modification tools
    if tool_name not in ("Write", "Edit", "MultiEdit"):
        return

    project_dir = os.environ.get("CLAUDE_PROJECT_DIR", "")
    if not project_dir:
        return

    dcc_path = "${agentcockpitPath}/.deltacodecube"
    if not os.path.isdir(dcc_path):
        return

    # Fire-and-forget reindex
    try:
        subprocess.Popen(
            ["uv", "run", "--directory", dcc_path, "python", "-c",
             f"from deltacodecube.db.database import get_connection; "
             f"from deltacodecube.cube import DeltaCodeCube; "
             f"conn = get_connection().__enter__(); "
             f"cube = DeltaCodeCube(conn); "
             f"cube.index_directory('{project_dir}')"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True
        )
    except Exception:
        pass  # Non-blocking, ignore errors

if __name__ == "__main__":
    main()
`;
}

/**
 * Install reindex hooks into a project
 */
export async function installReindexHooks(
  projectPath: string,
  agentcockpitPath: string
): Promise<HookResult> {
  try {
    // 1. Ensure .claude/hooks directory exists
    const hooksDir = `${projectPath}/.claude/hooks`;
    const hooksDirExists = await exists(hooksDir);
    if (!hooksDirExists) {
      await mkdir(hooksDir, { recursive: true });
    }

    // 2. Write reindex hook script
    const hookPath = `${hooksDir}/reindex_trigger.py`;
    const hookScript = generateReindexHookScript(agentcockpitPath);
    await writeTextFile(hookPath, hookScript);

    // 3. Add PostToolUse hook to settings
    let settings = await readClaudeSettings(projectPath) || {};

    if (!settings.hooks) {
      settings.hooks = {};
    }

    const reindexHook: ClaudeHookConfig = {
      type: 'command',
      command: `python3 "$CLAUDE_PROJECT_DIR/.claude/hooks/reindex_trigger.py"`,
      timeout: 3
    };

    const reindexMatcher: ClaudeHookMatcher = {
      matcher: 'Write|Edit|MultiEdit',
      hooks: [reindexHook]
    };

    // Filter out previous reindex hooks
    const existingPostToolUse = (settings.hooks.PostToolUse || []).filter(
      matcher => !matcher.hooks.some(h => h.command.includes('reindex_trigger'))
    );

    settings.hooks.PostToolUse = [...existingPostToolUse, reindexMatcher];

    const success = await writeClaudeSettings(projectPath, settings);
    if (!success) {
      return { success: false, error: 'Failed to write settings.json' };
    }

    console.log('[HookService] Reindex hooks installed successfully');
    return { success: true };
  } catch (e) {
    const error = e instanceof Error ? e.message : String(e);
    console.error('[HookService] Reindex install error:', error);
    return { success: false, error };
  }
}

/**
 * Uninstall reindex hooks from a project
 */
export async function uninstallReindexHooks(projectPath: string): Promise<HookResult> {
  try {
    const settings = await readClaudeSettings(projectPath);

    if (settings && settings.hooks) {
      if (settings.hooks.PostToolUse) {
        settings.hooks.PostToolUse = settings.hooks.PostToolUse.filter(
          matcher => !matcher.hooks.some(h => h.command.includes('reindex_trigger'))
        );

        if (settings.hooks.PostToolUse.length === 0) {
          delete settings.hooks.PostToolUse;
        }
      }

      if (Object.keys(settings.hooks).length === 0) {
        delete settings.hooks;
      }

      await writeClaudeSettings(projectPath, settings);
    }

    // Remove hook script
    const hookPath = `${projectPath}/.claude/hooks/reindex_trigger.py`;
    const hookExists = await exists(hookPath);
    if (hookExists) {
      await remove(hookPath);
    }

    console.log('[HookService] Reindex hooks uninstalled successfully');
    return { success: true };
  } catch (e) {
    const error = e instanceof Error ? e.message : String(e);
    console.error('[HookService] Reindex uninstall error:', error);
    return { success: false, error };
  }
}

/**
 * Check if reindex hooks are installed in a project
 */
export async function isReindexHooksInstalled(projectPath: string): Promise<boolean> {
  try {
    const settings = await readClaudeSettings(projectPath);
    if (!settings || !settings.hooks || !settings.hooks.PostToolUse) {
      return false;
    }
    return settings.hooks.PostToolUse.some(
      matcher => matcher.hooks.some(h => h.command.includes('reindex_trigger'))
    );
  } catch {
    return false;
  }
}

// ============================================
// AS.md — Autonomous Strategy Injection
// ============================================

/**
 * Returns the content of AS.md (Autonomous Strategy framework)
 */
export function generateAsMarkdown(): string {
  return `<!-- AgentCockpit: This file is required for the workflow manager to function correctly.
     Removing it is not recommended. More info: https://github.com/Rixmerz/agentcockpit -->

# AS — Autonomous Strategy

Before responding to any request, consciously evaluate which strategy is best:

## 1. Does it require structure?

**Direct response** if:
- Knowledge question, explanation, or isolated debug
- Obvious 1-3 line change

**Structure needed** if:
- Feature implementation spanning multiple files
- Refactor with regression risk
- Multi-phase process (complex debugging, analysis, deployment)

## 2. If structure is needed: Plan Mode or Workflow?

**Plan Mode** when:
- The result is new or modified code/files
- Architectural decisions need user approval before execution
- The task is one-off, not recurrent

**Workflow** when:
- The process has well-defined phases (e.g. understand → reproduce → fix → verify)
- It is a recurrent type of work (debugging, code review, feature dev)
- Phase enforcement matters — you must not skip steps

### Why workflows are powerful

Workflows unlock capabilities beyond simple plan mode:

- **Context persistence across very long tasks**: A workflow maintains shared state and context across an entire task set, even when individual sessions would normally lose context. You can resume mid-flow without losing where you left off.
- **Context injection**: Each workflow node can inject specific context (files, instructions, constraints) automatically — you always have exactly the right information for the current phase.
- **Dynamic context injection via DCC (Delta Code Cube)**: DCC tracks code changes in real time and injects relevant diffs and metrics into the workflow context. You always know what changed, when, and how much — no manual diffing needed.
- **Memory injections for edits**: Valuable patterns, past mistakes, and project-specific conventions are injected as memory at the right moment, so each edit benefits from accumulated project knowledge.

These advantages make workflows the right choice for any multi-step process where quality, traceability, or context depth matters.

## 3. If Workflow: Reuse or Create?

First list available workflows using the workflow manager tool.

**Reuse** if one already covers the case (e.g. \`debug\` for bugs, \`feature-dev\` for features).

**Create a new one** if the process is unique to this project. Use \`/pipeline-manager-init\` to build it interactively.

## 4. Action

- **Direct response**: Just respond.
- **Plan mode**: Say "entering plan mode" and use EnterPlanMode.
- **Existing workflow**: Activate it and proceed through its phases.
- **New workflow**: Create it first, then activate it.

> This decision is yours. Do not ask the user which to prefer unless you genuinely cannot decide.
`;
}

/**
 * Install AS.md into the user's project and reference it from CLAUDE.md
 */
export async function installAsMarkdown(projectPath: string): Promise<void> {
  try {
    // 1. Ensure .claude directory exists
    const claudeDir = `${projectPath}/.claude`;
    const claudeDirExists = await exists(claudeDir);
    if (!claudeDirExists) {
      await mkdir(claudeDir, { recursive: true });
    }

    // 2. Write AS.md
    const asPath = `${claudeDir}/AS.md`;
    await writeTextFile(asPath, generateAsMarkdown());
    console.log('[HookService] AS.md written to', asPath);

    // 3. Update CLAUDE.md
    const claudeMdPath = `${projectPath}/CLAUDE.md`;
    const claudeMdExists = await exists(claudeMdPath);
    const reference = '@.claude/AS.md';
    const prefix = `<!-- AgentCockpit workflow manager — do not remove this line -->\n${reference}\n`;

    if (claudeMdExists) {
      const content = await readTextFile(claudeMdPath);
      if (content.includes(reference)) {
        // Already has the reference — idempotent
        return;
      }
      // Prepend reference with blank line separator
      await writeTextFile(claudeMdPath, `${prefix}\n${content}`);
    } else {
      // Create minimal CLAUDE.md
      await writeTextFile(claudeMdPath, prefix);
    }
    console.log('[HookService] CLAUDE.md updated with AS.md reference');
  } catch (e) {
    console.error('[HookService] installAsMarkdown error:', e);
  }
}

export async function syncWorkflowHooks(
  projectPath: string,
  enabled: boolean,
  steps: WorkflowStep[]
): Promise<HookResult> {
  try {
    // Ensure hooks are installed first (if not already)
    const isInstalled = await isWorkflowHooksInstalled(projectPath);
    if (!isInstalled && enabled) {
      // First time enabling - do full install
      return await installWorkflowHooks(projectPath, steps);
    }

    // Write config.json with enforcer_enabled flag
    const workflowDir = `${projectPath}/.claude/workflow`;
    const configPath = `${workflowDir}/config.json`;

    // Ensure workflow directory exists
    const dirExists = await exists(workflowDir);
    if (!dirExists) {
      await mkdir(workflowDir, { recursive: true });
    }

    // Read existing config or create new
    let config: Record<string, unknown> = {};
    const configExists = await exists(configPath);
    if (configExists) {
      try {
        const content = await readTextFile(configPath);
        config = JSON.parse(content);
      } catch {
        config = {};
      }
    }

    // Update enforcer_enabled flag
    config.enforcer_enabled = enabled;
    config.last_updated = new Date().toISOString();

    await writeTextFile(configPath, JSON.stringify(config, null, 2));
    console.log('[HookService] Workflow enforcer', enabled ? 'enabled' : 'disabled');

    return { success: true };
  } catch (e) {
    const error = e instanceof Error ? e.message : String(e);
    console.error('[HookService] Sync error:', error);
    return { success: false, error };
  }
}
