#!/usr/bin/env python3
"""
DeltaCodeCube Reindex Hook for Claude Code
Generated by AgentCockpit

Triggers a non-blocking reindex after file modifications.
"""

import json
import sys
import subprocess
import os

def main():
    # Read hook input from stdin
    try:
        hook_input = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        return

    tool_name = hook_input.get("tool_name", "")

    # Only trigger on file modification tools
    if tool_name not in ("Write", "Edit", "MultiEdit"):
        return

    project_dir = os.environ.get("CLAUDE_PROJECT_DIR", "")
    if not project_dir:
        return

    dcc_path = "{{AGENTCOCKPIT_PATH}}/.deltacodecube"
    if not os.path.isdir(dcc_path):
        return

    # Fire-and-forget reindex
    try:
        subprocess.Popen(
            ["uv", "run", "--directory", dcc_path, "python", "-c",
             f"from deltacodecube.db.database import get_connection; "
             f"from deltacodecube.cube import DeltaCodeCube; "
             f"conn = get_connection().__enter__(); "
             f"cube = DeltaCodeCube(conn); "
             f"cube.index_directory('{project_dir}')"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True
        )
    except Exception:
        pass  # Non-blocking, ignore errors

if __name__ == "__main__":
    main()
